# Generated by Django 3.0.2 on 2020-01-28 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_name', models.CharField(max_length=100)),
                ('english_name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PublicHoliday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_name', models.CharField(max_length=200)),
                ('english_name', models.CharField(max_length=200)),
                ('holiday_date', models.DateTimeField(verbose_name='date of holiday')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='holiday_core.Country')),
            ],
        ),
    ]
