# Generated by Django 3.0.2 on 2020-01-28 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holiday_core', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='publicholiday',
            constraint=models.UniqueConstraint(fields=('holiday_date', 'local_name'), name='unique holiday'),
        ),
    ]
